api_platform:
  title: Test Api
  version: 1.0.0
  formats:
    jsonld: ["application/ld+json"]
  docs_formats:
    jsonld: ["application/ld+json"]
    jsonopenapi: ["application/vnd.openapi+json"]
    html: ["text/html"]
  defaults:
    stateless: true
    pagination_client_enabled: true
    pagination_items_per_page: 2
    pagination_enabled: false
    collection:
      pagination:
        items_per_page_parameter_name: itemsPerPage
        enabled_parameter_name: pagination
    cache_headers:
      vary: ["Content-Type", "Authorization", "Origin"]
    extra_properties:
      standard_put: true
      rfc_7807_compliant_errors: true
  keep_legacy_inflector: false
  use_symfony_listeners: true
  graphql:
    graphiql:
      enabled: false
